<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Finance\Customer;
use Illuminate\Pagination\LengthAwarePaginator;
use Illuminate\Support\Collection;

class ProductAssetController extends Controller
{
    public function index(Request $request)
    {
        // ── Mock product data (replace with DB query when ready) ──
        $allProducts = collect([
            ['code'=>'006671113','product_name'=>'3M CREAM CLEANSER MILL ...','cost_price'=>123750,'price_gr'=>null,'price_ec'=>null,'min_stock'=>1,'stock'=>16,'on_order'=>0,'discontinue'=>false, 'category'=>'CHEMICAL', 'supplier'=>'LAIN-LAIN', 'model'=>'LIQUID', 'quality'=>'POWDER 2.5KG', 'internal_code'=>'006671113', 'ext_code'=>'EX-6671', 'unit'=>'PCS', 'volume'=>1, 'not_for_count'=>false, 'services'=>false, 'inv_account'=>'PERSEDIAAN BARANG', 'cogs_account'=>'HARGA POKOK PENJUALAN', 'cost_center'=>'GA', 'account_dept'=>'DEPT-001', 'sales_price'=>150000, 'note'=>'Cream cleanser for general use', 'on_transit'=>0, 'balance'=>16],
            ['code'=>'0060281','product_name'=>'5 EXTRA POWDER','cost_price'=>300000,'price_gr'=>null,'price_ec'=>null,'min_stock'=>1,'stock'=>0,'on_order'=>5,'discontinue'=>false, 'category'=>'CHEMICAL', 'supplier'=>'PT. MEGA SUPPLIER', 'model'=>'POWDER', 'quality'=>'POWDER 6KG', 'internal_code'=>'0060281', 'ext_code'=>'EX-6028', 'unit'=>'BAG', 'volume'=>5, 'not_for_count'=>false, 'services'=>false, 'inv_account'=>'PERSEDIAAN BARANG', 'cogs_account'=>'HARGA POKOK PENJUALAN', 'cost_center'=>'OPERATIONS', 'account_dept'=>'DEPT-002', 'sales_price'=>350000, 'note'=>'Extra clean powder', 'on_transit'=>5, 'balance'=>0],
            ['code'=>'008950196','product_name'=>'A- PAD MERAH','cost_price'=>828754,'price_gr'=>null,'price_ec'=>null,'min_stock'=>1,'stock'=>38,'on_order'=>9,'discontinue'=>false, 'category'=>'ACCESSORIES', 'supplier'=>'CV. BERKAH JAYA', 'model'=>'DRY CHEMICAL', 'quality'=>'RED', 'internal_code'=>'008950196', 'ext_code'=>'EX-8950', 'unit'=>'PCS', 'volume'=>1, 'not_for_count'=>false, 'services'=>false, 'inv_account'=>'BIAYA KEBERSIHAN', 'cogs_account'=>'HUTANG VENDOR', 'cost_center'=>'GA', 'account_dept'=>'DEPT-003', 'sales_price'=>900000, 'note'=>'Red pad for scrubbing', 'on_transit'=>0, 'balance'=>38],
            ['code'=>'009950028','product_name'=>'A-BOWL CLEANER','cost_price'=>592176,'price_gr'=>null,'price_ec'=>null,'min_stock'=>1,'stock'=>290,'on_order'=>17,'discontinue'=>false, 'category'=>'CHEMICAL', 'supplier'=>'PT. SUMBER MAKMUR', 'model'=>'LIQUID', 'quality'=>'GREEN', 'internal_code'=>'009950028', 'ext_code'=>'EX-9950', 'unit'=>'PCS', 'volume'=>1, 'not_for_count'=>false, 'services'=>false, 'inv_account'=>'PERSEDIAAN BARANG', 'cogs_account'=>'HARGA POKOK PENJUALAN', 'cost_center'=>'FINANCE', 'account_dept'=>'DEPT-001', 'sales_price'=>650000, 'note'=>'Bowl cleaner for hygiene', 'on_transit'=>0, 'balance'=>290],
            ['code'=>'009950518','product_name'=>'A-BRUSH TANGKAI','cost_price'=>25000,'price_gr'=>null,'price_ec'=>null,'min_stock'=>1,'stock'=>0,'on_order'=>3,'discontinue'=>false, 'category'=>'ACCESSORIES', 'supplier'=>'LAIN-LAIN', 'model'=>'DRY CHEMICAL', 'quality'=>'BLACK', 'internal_code'=>'009950518', 'ext_code'=>'EX-9951', 'unit'=>'PCS', 'volume'=>1, 'not_for_count'=>false, 'services'=>false, 'inv_account'=>'BIAYA KEBERSIHAN', 'cogs_account'=>'HUTANG VENDOR', 'cost_center'=>'GA', 'account_dept'=>'', 'sales_price'=>35000, 'note'=>'Long handle brush', 'on_transit'=>0, 'balance'=>0],
            ['code'=>'0210269804','product_name'=>'AC COIL CLEANER STANDART ...','cost_price'=>24500,'price_gr'=>null,'price_ec'=>null,'min_stock'=>1,'stock'=>120,'on_order'=>0,'discontinue'=>false, 'category'=>'CHEMICAL', 'supplier'=>'PT. MEGA SUPPLIER', 'model'=>'LIQUID', 'quality'=>'POWDER 2.5KG', 'internal_code'=>'0210269804', 'ext_code'=>'EX-2102', 'unit'=>'PCS', 'volume'=>1, 'not_for_count'=>false, 'services'=>false, 'inv_account'=>'PERSEDIAAN BARANG', 'cogs_account'=>'HARGA POKOK PENJUALAN', 'cost_center'=>'OPERATIONS', 'account_dept'=>'DEPT-001', 'sales_price'=>30000, 'note'=>'AC Maintenance', 'on_transit'=>0, 'balance'=>120],
            ['code'=>'009140269150','product_name'=>'AC DAIKIN 1 PK FTC25NV14','cost_price'=>3950000,'price_gr'=>null,'price_ec'=>null,'min_stock'=>1,'stock'=>0,'on_order'=>1,'discontinue'=>false, 'category'=>'MECHANICAL', 'supplier'=>'CV. BERKAH JAYA', 'model'=>'WATER', 'quality'=>'WHITE', 'internal_code'=>'009140269150', 'ext_code'=>'EX-9140', 'unit'=>'SET', 'volume'=>1, 'not_for_count'=>false, 'services'=>false, 'inv_account'=>'ASET TETAP', 'cogs_account'=>'BEBAN POKOK', 'cost_center'=>'GA', 'account_dept'=>'DEPT-002', 'sales_price'=>4500000, 'note'=>'Air Conditioner', 'on_transit'=>0, 'balance'=>0],
            ['code'=>'008140269205','product_name'=>'AC DAIKIN 1 PK THAILAND FTC...','cost_price'=>3600000,'price_gr'=>null,'price_ec'=>null,'min_stock'=>1,'stock'=>0,'on_order'=>2,'discontinue'=>false, 'category'=>'MECHANICAL', 'supplier'=>'PT. SUMBER MAKMUR', 'model'=>'WATER', 'quality'=>'WHITE', 'internal_code'=>'008140269205', 'ext_code'=>'EX-8140', 'unit'=>'SET', 'volume'=>1, 'not_for_count'=>false, 'services'=>false, 'inv_account'=>'ASET TETAP', 'cogs_account'=>'BEBAN POKOK', 'cost_center'=>'IT', 'account_dept'=>'DEPT-001', 'sales_price'=>4000000, 'note'=>'Thai version AC', 'on_transit'=>0, 'balance'=>0],
            ['code'=>'018140275154','product_name'=>'AC DAIKIN FREON R 410','cost_price'=>35000,'price_gr'=>null,'price_ec'=>null,'min_stock'=>1,'stock'=>0,'on_order'=>200,'discontinue'=>false, 'category'=>'CHEMICAL', 'supplier'=>'LAIN-LAIN', 'model'=>'GAS', 'quality'=>'GREEN', 'internal_code'=>'018140275154', 'ext_code'=>'EX-1814', 'unit'=>'KG', 'volume'=>1, 'not_for_count'=>false, 'services'=>false, 'inv_account'=>'BIAYA OPERASIONAL', 'cogs_account'=>'HUTANG VENDOR', 'cost_center'=>'GA', 'account_dept'=>'', 'sales_price'=>50000, 'note'=>'Freon refill', 'on_transit'=>0, 'balance'=>0],
            ['code'=>'018140865645','product_name'=>'AC DAIKIN FTKQ50 2PK','cost_price'=>8350000,'price_gr'=>null,'price_ec'=>null,'min_stock'=>1,'stock'=>0,'on_order'=>1,'discontinue'=>false, 'category'=>'MECHANICAL', 'supplier'=>'PT. MEGA SUPPLIER', 'model'=>'WATER', 'quality'=>'WHITE', 'internal_code'=>'018140865645', 'ext_code'=>'EX-8656', 'unit'=>'SET', 'volume'=>1, 'not_for_count'=>false, 'services'=>false, 'inv_account'=>'ASET TETAP', 'cogs_account'=>'BEBAN POKOK', 'cost_center'=>'OPERATIONS', 'account_dept'=>'DEPT-003', 'sales_price'=>9500000, 'note'=>'Large AC unit', 'on_transit'=>0, 'balance'=>0],
            ['code'=>'018141182941','product_name'=>'AC DAIKIN INDOOR WALL MOU...','cost_price'=>13302500,'price_gr'=>null,'price_ec'=>null,'min_stock'=>1,'stock'=>0,'on_order'=>1,'discontinue'=>false, 'category'=>'MECHANICAL', 'supplier'=>'CV. BERKAH JAYA', 'model'=>'WATER', 'quality'=>'WHITE', 'internal_code'=>'018141182941', 'ext_code'=>'EX-1182', 'unit'=>'SET', 'volume'=>1, 'not_for_count'=>false, 'services'=>false, 'inv_account'=>'ASET TETAP', 'cogs_account'=>'BEBAN POKOK', 'cost_center'=>'GA', 'account_dept'=>'DEPT-001', 'sales_price'=>15000000, 'note'=>'Indoor wall mount unit', 'on_transit'=>0, 'balance'=>0],
            ['code'=>'018140463','product_name'=>'AC DAIKIN PERBAIKAN PIPA KA...','cost_price'=>1700000,'price_gr'=>null,'price_ec'=>null,'min_stock'=>1,'stock'=>0,'on_order'=>1,'discontinue'=>false, 'category'=>'MECHANICAL', 'supplier'=>'PT. SUMBER MAKMUR', 'model'=>'SERVICES', 'quality'=>'WATER', 'internal_code'=>'018140463', 'ext_code'=>'EX-1814', 'unit'=>'SERVICES', 'volume'=>1, 'not_for_count'=>true, 'services'=>true, 'inv_account'=>'BIAYA OPERASIONAL', 'cogs_account'=>'HUTANG VENDOR', 'cost_center'=>'OPERATIONS', 'account_dept'=>'DEPT-002', 'sales_price'=>2000000, 'note'=>'Repair service', 'on_transit'=>0, 'balance'=>0],
            ['code'=>'001140358','product_name'=>'ACCESSORIES','cost_price'=>1,'price_gr'=>null,'price_ec'=>null,'min_stock'=>1,'stock'=>0,'on_order'=>1,'discontinue'=>false, 'category'=>'ACCESSORIES', 'supplier'=>'LAIN-LAIN', 'model'=>'DRY CHEMICAL', 'quality'=>'RED', 'internal_code'=>'001140358', 'ext_code'=>'EX-1140', 'unit'=>'PCS', 'volume'=>1, 'not_for_count'=>false, 'services'=>false, 'inv_account'=>'BIAYA KEBERSIHAN', 'cogs_account'=>'HUTANG VENDOR', 'cost_center'=>'', 'account_dept'=>'', 'sales_price'=>5, 'note'=>'General accessory', 'on_transit'=>0, 'balance'=>0],
            ['code'=>'0010328','product_name'=>'ACCESSORIES  KUAS 3"','cost_price'=>15000,'price_gr'=>null,'price_ec'=>null,'min_stock'=>1,'stock'=>0,'on_order'=>0,'discontinue'=>false, 'category'=>'ACCESSORIES', 'supplier'=>'PT. MEGA SUPPLIER', 'model'=>'DRY CHEMICAL', 'quality'=>'BLACK', 'internal_code'=>'0010328', 'ext_code'=>'EX-1032', 'unit'=>'PCS', 'volume'=>1, 'not_for_count'=>false, 'services'=>false, 'inv_account'=>'BIAYA KEBERSIHAN', 'cogs_account'=>'HUTANG VENDOR', 'cost_center'=>'GA', 'account_dept'=>'DEPT-001', 'sales_price'=>20000, 'note'=>'Paint brush 3 inch', 'on_transit'=>0, 'balance'=>0],
            ['code'=>'001000857810','product_name'=>'ACCESSORIES Z POMPA GRUN...','cost_price'=>5700000,'price_gr'=>null,'price_ec'=>null,'min_stock'=>1,'stock'=>0,'on_order'=>0,'discontinue'=>false, 'category'=>'ACCESSORIES', 'supplier'=>'CV. BERKAH JAYA', 'model'=>'DRY CHEMICAL', 'quality'=>'WHITE', 'internal_code'=>'001000857810', 'ext_code'=>'EX-8578', 'unit'=>'PCS', 'volume'=>1, 'not_for_count'=>false, 'services'=>false, 'inv_account'=>'BIAYA KEBERSIHAN', 'cogs_account'=>'HUTANG VENDOR', 'cost_center'=>'OPERATIONS', 'account_dept'=>'DEPT-003', 'sales_price'=>6500000, 'note'=>'Pump accessory', 'on_transit'=>0, 'balance'=>0],
            ['code'=>'008670835','product_name'=>'ACRYLIC URINOIR','cost_price'=>45000,'price_gr'=>null,'price_ec'=>null,'min_stock'=>1,'stock'=>0,'on_order'=>15,'discontinue'=>false, 'category'=>'FURNITURE', 'supplier'=>'PT. SUMBER MAKMUR', 'model'=>'WATER', 'quality'=>'WHITE', 'internal_code'=>'008670835', 'ext_code'=>'EX-8670', 'unit'=>'PCS', 'volume'=>1, 'not_for_count'=>false, 'services'=>false, 'inv_account'=>'ASET TETAP', 'cogs_account'=>'BEBAN POKOK', 'cost_center'=>'GA', 'account_dept'=>'DEPT-001', 'sales_price'=>55000, 'note'=>'Urinoir replacement', 'on_transit'=>0, 'balance'=>0],
            ['code'=>'001000100250','product_name'=>'AIR FILTER COMPRESOR','cost_price'=>850000,'price_gr'=>null,'price_ec'=>null,'min_stock'=>2,'stock'=>3,'on_order'=>0,'discontinue'=>false, 'category'=>'MECHANICAL', 'supplier'=>'LAIN-LAIN', 'model'=>'FOAM', 'quality'=>'BLACK', 'internal_code'=>'001000100250', 'ext_code'=>'EX-1000', 'unit'=>'PCS', 'volume'=>1, 'not_for_count'=>false, 'services'=>false, 'inv_account'=>'PERSEDIAAN BARANG', 'cogs_account'=>'HARGA POKOK PENJUALAN', 'cost_center'=>'OPERATIONS', 'account_dept'=>'DEPT-002', 'sales_price'=>1000000, 'note'=>'Compressor filter', 'on_transit'=>0, 'balance'=>3],
            ['code'=>'009950120','product_name'=>'AJAX POWDER LEMON 900GR','cost_price'=>18500,'price_gr'=>null,'price_ec'=>null,'min_stock'=>5,'stock'=>12,'on_order'=>0,'discontinue'=>false, 'category'=>'CHEMICAL', 'supplier'=>'PT. MEGA SUPPLIER', 'model'=>'POWDER', 'quality'=>'YELLOW', 'internal_code'=>'009950120', 'ext_code'=>'EX-9952', 'unit'=>'BAG', 'volume'=>1, 'not_for_count'=>false, 'services'=>false, 'inv_account'=>'PERSEDIAAN BARANG', 'cogs_account'=>'HARGA POKOK PENJUALAN', 'cost_center'=>'GA', 'account_dept'=>'DEPT-001', 'sales_price'=>25000, 'note'=>'Ajax cleaning powder', 'on_transit'=>0, 'balance'=>12],
            ['code'=>'008140001010','product_name'=>'AMPERE METER PANEL','cost_price'=>175000,'price_gr'=>null,'price_ec'=>null,'min_stock'=>1,'stock'=>2,'on_order'=>0,'discontinue'=>false, 'category'=>'ELECTRICAL', 'supplier'=>'CV. BERKAH JAYA', 'model'=>'FOAM', 'quality'=>'BLACK', 'internal_code'=>'008140001010', 'ext_code'=>'EX-8140', 'unit'=>'PCS', 'volume'=>1, 'not_for_count'=>false, 'services'=>false, 'inv_account'=>'PERSEDIAAN BARANG', 'cogs_account'=>'HUTANG VENDOR', 'cost_center'=>'IT', 'account_dept'=>'DEPT-001', 'sales_price'=>200000, 'note'=>'Ampere meter for panel', 'on_transit'=>0, 'balance'=>2],
            ['code'=>'009140005501','product_name'=>'ANTI RAYAP RENTOKIL 500ML','cost_price'=>95000,'price_gr'=>null,'price_ec'=>null,'min_stock'=>3,'stock'=>6,'on_order'=>0,'discontinue'=>false, 'category'=>'CHEMICAL', 'supplier'=>'PT. SUMBER MAKMUR', 'model'=>'LIQUID', 'quality'=>'YELLOW', 'internal_code'=>'009140005501', 'ext_code'=>'EX-9140', 'unit'=>'BOT', 'volume'=>1, 'not_for_count'=>false, 'services'=>false, 'inv_account'=>'PERSEDIAAN BARANG', 'cogs_account'=>'HARGA POKOK PENJUALAN', 'cost_center'=>'GA', 'account_dept'=>'DEPT-001', 'sales_price'=>120000, 'note'=>'Anti termite liquid', 'on_transit'=>0, 'balance'=>6],
            ['code'=>'001000200100','product_name'=>'AQUA GALON 19L','cost_price'=>20000,'price_gr'=>null,'price_ec'=>null,'min_stock'=>10,'stock'=>24,'on_order'=>5,'discontinue'=>false, 'category'=>'CHEMICAL', 'supplier'=>'LAIN-LAIN', 'model'=>'WATER', 'quality'=>'BLUE', 'internal_code'=>'001000200100', 'ext_code'=>'EX-1000', 'unit'=>'GALON', 'volume'=>19, 'not_for_count'=>false, 'services'=>false, 'inv_account'=>'BIAYA KEBERSIHAN', 'cogs_account'=>'HUTANG VENDOR', 'cost_center'=>'GA', 'account_dept'=>'', 'sales_price'=>22000, 'note'=>'Drinking water', 'on_transit'=>5, 'balance'=>24],
            ['code'=>'007000300200','product_name'=>'BAUT HEX M10x50','cost_price'=>2500,'price_gr'=>null,'price_ec'=>null,'min_stock'=>20,'stock'=>150,'on_order'=>0,'discontinue'=>false, 'category'=>'ACCESSORIES', 'supplier'=>'PT. MEGA SUPPLIER', 'model'=>'DRY CHEMICAL', 'quality'=>'BLACK', 'internal_code'=>'007000300200', 'ext_code'=>'EX-7000', 'unit'=>'PCS', 'volume'=>1, 'not_for_count'=>false, 'services'=>false, 'inv_account'=>'BIAYA KEBERSIHAN', 'cogs_account'=>'HUTANG VENDOR', 'cost_center'=>'OPERATIONS', 'account_dept'=>'DEPT-003', 'sales_price'=>3000, 'note'=>'Hex bolt', 'on_transit'=>0, 'balance'=>150],
            ['code'=>'003000900110','product_name'=>'BEARING SKF 6205 2RS','cost_price'=>45000,'price_gr'=>null,'price_ec'=>null,'min_stock'=>5,'stock'=>22,'on_order'=>4,'discontinue'=>false, 'category'=>'MECHANICAL', 'supplier'=>'CV. BERKAH JAYA', 'model'=>'FOAM', 'quality'=>'BLACK', 'internal_code'=>'003000900110', 'ext_code'=>'EX-3000', 'unit'=>'PCS', 'volume'=>1, 'not_for_count'=>false, 'services'=>false, 'inv_account'=>'PERSEDIAAN BARANG', 'cogs_account'=>'HUTANG VENDOR', 'cost_center'=>'OPERATIONS', 'account_dept'=>'DEPT-002', 'sales_price'=>55000, 'note'=>'SKF Bearing', 'on_transit'=>4, 'balance'=>22],
            ['code'=>'009101010000','product_name'=>'CAIRAN WD-40 360ML','cost_price'=>65000,'price_gr'=>null,'price_ec'=>null,'min_stock'=>3,'stock'=>8,'on_order'=>2,'discontinue'=>false, 'category'=>'CHEMICAL', 'supplier'=>'PT. SUMBER MAKMUR', 'model'=>'LIQUID', 'quality'=>'YELLOW', 'internal_code'=>'009101010000', 'ext_code'=>'EX-9101', 'unit'=>'BOT', 'volume'=>1, 'not_for_count'=>false, 'services'=>false, 'inv_account'=>'PERSEDIAAN BARANG', 'cogs_account'=>'HARGA POKOK PENJUALAN', 'cost_center'=>'GA', 'account_dept'=>'DEPT-001', 'sales_price'=>75000, 'note'=>'WD-40 Lubricant', 'on_transit'=>2, 'balance'=>8],
            ['code'=>'004000310011','product_name'=>'CAIRAN PEMBERSIH LANTAI 5L','cost_price'=>85000,'price_gr'=>null,'price_ec'=>null,'min_stock'=>3,'stock'=>12,'on_order'=>0,'discontinue'=>false, 'category'=>'CHEMICAL', 'supplier'=>'LAIN-LAIN', 'model'=>'LIQUID', 'quality'=>'YELLOW', 'internal_code'=>'004000310011', 'ext_code'=>'EX-4000', 'unit'=>'GALON', 'volume'=>5, 'not_for_count'=>false, 'services'=>false, 'inv_account'=>'BIAYA OPERASIONAL', 'cogs_account'=>'HUTANG VENDOR', 'cost_center'=>'GA', 'account_dept'=>'DEPT-001', 'sales_price'=>95000, 'note'=>'Floor cleaner 5L', 'on_transit'=>0, 'balance'=>12],
        ])->map(fn($p, $i) => (object)array_merge($p, ['id' => $i + 1]));

        $perPage = 50;
        $page    = $request->input('page', 1);
        $slice   = $allProducts->slice(($page - 1) * $perPage, $perPage)->values();

        $products = new LengthAwarePaginator(
            $slice,
            $allProducts->count(),
            $perPage,
            $page,
            ['path' => $request->url(), 'query' => $request->query()]
        );

        $customers = Customer::all(['id', 'counter_name', 'code']);

        return view('inventory.product_assets.index', compact('products', 'customers'));
    }

    public function getDetails($id)
    {
        // Mock detail response for API calls (fallback)
        return response()->json([
            'code'          => $id,
            'last_received' => now()->subDays(rand(1, 30))->toDateString(),
            'last_issued'   => now()->subDays(rand(1, 15))->toDateString(),
            'last_sold'     => now()->subDays(rand(1, 60))->toDateString(),
            'ytd_received'  => rand(50, 500),
            'ytd_issued'    => rand(10, 200),
            'activities'    => [],
            'warehouses'    => [],
        ]);
    }
}
